apiVersion: v1
kind: Pod
metadata:
  name: cmdemo
  labels:
    app: volumes
spec:
  containers:
    - name: container1
      image: busybox
      volumeMounts:
        - name: myvol
          mountPath: /modi
      args:
       - /bin/sh
       - -c
       - "while true; do date; echo Hello from Kubernetes; done"
  volumes:
    - name: myvol
      configMap:
        name: mycm 
