apiVersion: v1
kind: Pod
metadata:
  name: hostpathdemo
  labels:
    app: volumes
spec:
  containers:
    - name: container1
      image: nginx:1.15.5
      volumeMounts:
        - name: myvol
          mountPath: /ritesh
          readOnly: false
    - name: container2
      image: busybox
      volumeMounts:
        - name: myvol
          mountPath: /modi
          readOnly: false
      args:
       - /bin/sh
       - -c
       - "while true; do date; echo Hello from Kubernetes; done"
  volumes:
    - name: myvol
      hostPath:
        path: /nodepathtest
