apiVersion: v1
kind: ReplicationController
metadata: 
  name: myrc
  labels: 
    app: rcexample
spec:
  selector:
    app: rcpods
  replicas: 3
  template:
    metadata:
      name: rcanypod
      labels:
        app: rcpods
    spec:
      containers:
        - image: nginx:1.15.5
          name: container1
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
