apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: testpod
spec:
  containers:
    - name: container1
      image: nginx:1.17.5
      ports: 
        - name: http
          protocol: TCP
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: pod-service
spec:
  selector:
    app: testpod
  type: LoadBalancer
  ports:
    - name: http
      targetPort: 80
      port: 8080
