apiVersion: v1
kind: Pod
metadata:
  name: secretdemo
  labels:
    app: secrets
spec:
  containers:
    - name: container1
      image: busybox
      env:
        - name: myev1
          valueFrom:
            secretKeyRef: 
              name: mysecret
              key: resourcegroup
      args:
       - /bin/sh
       - -c
       - "while true; do date; echo Hello from $(myev1); done"

